name: 'Get environment variables'
description: 'Configures environment variables for a workflow'
runs:
  using: "composite"
  steps:
    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ./.github/env/variables.env
        key: ${{ runner.os }}-env

    - run: |
        sed "" ./.github/env/variables.env >> $GITHUB_ENV
      shell: bash
