name: Cyklone Modular Template KMM CI

on:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.GetVersion.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        run: echo "VERSION=$(git fetch --tags --quiet && git describe --tags --always --first-parent)" >> $GITHUB_ENV
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Version
        run : echo ${{ env.VERSION }}
