name: Cyklone Modular Template KMM CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        uses: ./.github/actions/setenv
        with:
          name: VERSION
          value: $(git fetch --tags --quiet && git describe --tags --always --first-parent)
  job2:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Get Version
        uses: ./.github/actions/getenv
      - name: Print Version
        run: echo ${{ env.VERSION }}
