name: Cyklone Modular Template KMM CI

on:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.GetVersion.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - id: GetVersion
        run: |
          echo "::set-output name=version::$(git fetch --tags --quiet && git describe --tags --always --first-parent)"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Version
        run : echo ${{needs.setup.outputs.version}}
